name: Auto Merge on Push

on:
  push:
    branches:
      - "*"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Merge changes
        uses: tzkhan/github-action-merge@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base: main
