name: Auto Merge on Push

on:
  push:
    branches:
      - "*"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge changes
        run: |
          git config user.name "Parasite-231"
          git config user.email "muktadir@iut-dhaka.edu"
          git checkout main
          git merge --no-ff ${{ github.ref }}
          git push origin main
