name: All Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  merge:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ needs.tests.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config user.name "Parasite-231"
          git config user.email "muktadir@iut-dhaka.edu"

      - name: Merge changes into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff ${{ github.sha }}
          git push origin main

      - name: Show git status
        run: |
          git status
